// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: clients.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createClient = `-- name: CreateClient :exec
INSERT INTO clients (user_id, name, phone, address)
VALUES ($1, $2, $3, $4)
`

type CreateClientParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Name    string    `json:"name"`
	Phone   string    `json:"phone"`
	Address string    `json:"address"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) error {
	_, err := q.db.Exec(ctx, createClient,
		arg.UserID,
		arg.Name,
		arg.Phone,
		arg.Address,
	)
	return err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, user_id, name, phone, address, created_at, updated_at
FROM clients
WHERE id = $1
`

func (q *Queries) GetClientByID(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientByUserID = `-- name: GetClientByUserID :one
SELECT id, user_id, name, phone, address, created_at, updated_at
FROM clients
WHERE user_id = $1
`

func (q *Queries) GetClientByUserID(ctx context.Context, userID uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByUserID, userID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT
    c.id,
    c.user_id,
    c.name,
    c.phone,
    c.address,
    c.created_at,
    c.updated_at,
    u.email
FROM clients c
JOIN users u ON u.id = c.user_id
ORDER BY c.created_at DESC
`

type ListClientsRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Name      string             `json:"name"`
	Phone     string             `json:"phone"`
	Address   string             `json:"address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Email     string             `json:"email"`
}

func (q *Queries) ListClients(ctx context.Context) ([]ListClientsRow, error) {
	rows, err := q.db.Query(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClientsRow
	for rows.Next() {
		var i ListClientsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Phone,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET name = $2,
    phone = $3,
    address = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, phone, address, created_at, updated_at
`

type UpdateClientParams struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	Phone   string    `json:"phone"`
	Address string    `json:"address"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Address,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
