// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateClient(ctx context.Context, arg CreateClientParams) error
	CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetClientByID(ctx context.Context, id uuid.UUID) (Client, error)
	GetClientByUserID(ctx context.Context, userID uuid.UUID) (Client, error)
	GetTicketByID(ctx context.Context, id uuid.UUID) (GetTicketByIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListClients(ctx context.Context) ([]ListClientsRow, error)
	ListTicketsForAdmin(ctx context.Context, dollar_1 string) ([]ListTicketsForAdminRow, error)
	ListTicketsForClient(ctx context.Context, arg ListTicketsForClientParams) ([]Ticket, error)
	UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) (Ticket, error)
}

var _ Querier = (*Queries)(nil)
