// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tickets.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (client_id, ticket_no, title, type, remarks, status)
VALUES ($1, $2, $3, $4, $5, 'new')
RETURNING id, client_id, ticket_no, title, type, remarks, status, created_at, updated_at
`

type CreateTicketParams struct {
	ClientID uuid.UUID `json:"client_id"`
	TicketNo string    `json:"ticket_no"`
	Title    string    `json:"title"`
	Type     string    `json:"type"`
	Remarks  string    `json:"remarks"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.ClientID,
		arg.TicketNo,
		arg.Title,
		arg.Type,
		arg.Remarks,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TicketNo,
		&i.Title,
		&i.Type,
		&i.Remarks,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketByID = `-- name: GetTicketByID :one
SELECT
    t.id,
    t.client_id,
    t.ticket_no,
    t.title,
    t.type,
    t.remarks,
    t.status,
    t.created_at,
    t.updated_at,
    c.user_id AS client_user_id
FROM tickets t
JOIN clients c ON c.id = t.client_id
WHERE t.id = $1
`

type GetTicketByIDRow struct {
	ID           uuid.UUID          `json:"id"`
	ClientID     uuid.UUID          `json:"client_id"`
	TicketNo     string             `json:"ticket_no"`
	Title        string             `json:"title"`
	Type         string             `json:"type"`
	Remarks      string             `json:"remarks"`
	Status       TicketStatus       `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ClientUserID uuid.UUID          `json:"client_user_id"`
}

func (q *Queries) GetTicketByID(ctx context.Context, id uuid.UUID) (GetTicketByIDRow, error) {
	row := q.db.QueryRow(ctx, getTicketByID, id)
	var i GetTicketByIDRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TicketNo,
		&i.Title,
		&i.Type,
		&i.Remarks,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientUserID,
	)
	return i, err
}

const listTicketsForAdmin = `-- name: ListTicketsForAdmin :many
SELECT
    t.id,
    t.client_id,
    t.ticket_no,
    t.title,
    t.type,
    t.remarks,
    t.status,
    t.created_at,
    t.updated_at,
    c.name AS client_name,
    u.email AS client_email
FROM tickets t
JOIN clients c ON c.id = t.client_id
JOIN users u ON u.id = c.user_id
WHERE ($1::text = '' OR t.status::text = $1::text)
ORDER BY t.created_at DESC
`

type ListTicketsForAdminRow struct {
	ID          uuid.UUID          `json:"id"`
	ClientID    uuid.UUID          `json:"client_id"`
	TicketNo    string             `json:"ticket_no"`
	Title       string             `json:"title"`
	Type        string             `json:"type"`
	Remarks     string             `json:"remarks"`
	Status      TicketStatus       `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ClientName  string             `json:"client_name"`
	ClientEmail string             `json:"client_email"`
}

func (q *Queries) ListTicketsForAdmin(ctx context.Context, dollar_1 string) ([]ListTicketsForAdminRow, error) {
	rows, err := q.db.Query(ctx, listTicketsForAdmin, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketsForAdminRow
	for rows.Next() {
		var i ListTicketsForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.TicketNo,
			&i.Title,
			&i.Type,
			&i.Remarks,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientName,
			&i.ClientEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsForClient = `-- name: ListTicketsForClient :many
SELECT
    t.id,
    t.client_id,
    t.ticket_no,
    t.title,
    t.type,
    t.remarks,
    t.status,
    t.created_at,
    t.updated_at
FROM tickets t
WHERE t.client_id = $1
    AND ($2::text = '' OR t.status::text = $2::text)
ORDER BY t.created_at DESC
`

type ListTicketsForClientParams struct {
	ClientID uuid.UUID `json:"client_id"`
	Column2  string    `json:"column_2"`
}

func (q *Queries) ListTicketsForClient(ctx context.Context, arg ListTicketsForClientParams) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsForClient, arg.ClientID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.TicketNo,
			&i.Title,
			&i.Type,
			&i.Remarks,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicketStatus = `-- name: UpdateTicketStatus :one
UPDATE tickets
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, client_id, ticket_no, title, type, remarks, status, created_at, updated_at
`

type UpdateTicketStatusParams struct {
	ID     uuid.UUID    `json:"id"`
	Status TicketStatus `json:"status"`
}

func (q *Queries) UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicketStatus, arg.ID, arg.Status)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TicketNo,
		&i.Title,
		&i.Type,
		&i.Remarks,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
